// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace carloancalculator {
	public class CarLoanCalculator : global::haxe.lang.HxObject {
		
		static CarLoanCalculator() {
			unchecked{
				#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588}, new string[]{"obj", "SuppressWarnings"});
				#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
				{
					#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
					{
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						global::carloancalculator.CarLoanCalculator.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public CarLoanCalculator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public CarLoanCalculator(global::maglev.MagLev maglev) {
			#line 14 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
			global::carloancalculator.CarLoanCalculator.__hx_ctor_carloancalculator_CarLoanCalculator(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_carloancalculator_CarLoanCalculator(global::carloancalculator.CarLoanCalculator __hx_this, global::maglev.MagLev maglev) {
			#line 15 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
			__hx_this.maglev = maglev;
		}
		#line default
		
		public static object __meta__;
		
		public global::maglev.MagLev maglev;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
				switch (hash) {
					case 858513194:
					{
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						return @value;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
				switch (hash) {
					case 858513194:
					{
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
			baseArr.push("maglev");
			#line 11 "/my-component/src/carloancalculator/CarLoanCalculator.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


